name = "EDCircuit"
uuid = "191323af-5f78-4ad7-b687-2ffd304748e5"
authors = ["Hugo LÃ³io"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Combinatorics = "1.0.2"
Dates = "1.11.0"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
SpecialFunctions = "2.4.0"
